### ISSUE TITLE
Any new release is planned?

### ISSUE THREAD

**Issue by steida** [mdlawson/piping#3]
Outdated dependencies:
chokidar                                      0.5.3                     0.5.3                    1.0.0-rc4  piping > chokidar
colors                                        0.6.2                     0.6.2                        1.0.3  piping > colors

**Comment by mdlawson** [comment]
Updated to latest stable versions, I'll update to chokidar 1.0.0 when it is released. I'm not working with node very much currently, so nothing new is planned for this module, but any pull requests are welcome!

**Comment by steida** [comment]
Thank you very much.
