### ISSUE TITLE
Add option to disable respawn on crash

### ISSUE THREAD

**Issue by mntnoe** [mdlawson/piping#7]
If the application crashes during upon starting up, `piping` will respawn the application immediately. 

    if (!require('piping')()) return
    console.log('running')
    crash()

This results in an infinite loop:

    running
    [piping] can't execute file: /home/mntnoe/Desktop/1/index.js
    [piping] error given was: ReferenceError: crash is not defined
        at Object.<anonymous> (/home/mntnoe/Desktop/1/index.js:3:1)
        ...
    [piping] further repeats of this error will be suppressed...
    running
    running
    running
    running
    ...
  
If I save something in my editor too soon and this happens, my CPU usage goes nuts. It would be nice to be able to specify that piping should wait for another file change before respawning the application.

Would that be possible?

**Comment by steida** [comment]
Unfortunately, I don't know. But keep experimenting and feel free to send pull request.

**Comment by mntnoe** [comment]
I have looked into it now and tweaked the behavior in a [fork](https://github.com/mntnoe/piping). With this tweak, the worker will only respawn upon file change. It should be possible to make a PR with this behavior behind an optional flag for backwards compatibility. We could also omit making it configurable for the sake of simplicity. This depends on if anybody currently uses the respawn-on-crash behavior.

**Comment by steida** [comment]
Great! Please send PR with optional new functionality. Thank you!

**Comment by mntnoe** [comment]
For reference: Submitted as pull request #8 .

**Comment by steida** [comment]
@mntnoe I don't have a time to maintain this. I can ask owner and make you a new maintainer. Does it works for you?

**Comment by mntnoe** [comment]
Sure, I guess I can help maintaining...

**Comment by steida** [comment]
So please write to mdlawson@gmx.com and ask him. That's how I was added as collaborator.

**Comment by mntnoe** [comment]
Solved in v0.3.0.
